---
title: "Tasa de desocupación"
author: "CEPAL"
date: "2023-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(samplesize4surveys)
library(readxl)
library(writexl)
```



```{r}
f_tablaMue <- function(str_region){
  temp <-  df_parametrostablas %>% filter(Agregacion == str_region) 
  
  N <- temp$N
  M <- temp$M
  P = temp$P
  cve <- temp$cve
  conf <- temp$conf
  r1 <- temp$r1
  r2 <- temp$r2
  b <-  temp$b  # Personas por hogar
  deff <- temp$deff
  
  nro_vivXUPM <- temp$nro_vivXUPM
  PM <- temp$PM # Perdida de Muestra
  TR <- temp$TR # Tasa de resupesta
  
  # Calculamos alpha, z, icc
  r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
  nbarra_encuesta <- nro_vivXUPM * b * r # Personas
  alpha <- 1 - conf
  z <- qnorm(1-alpha/2)
  icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
    
  # Tabla de muestreo 
  tabla_mue <- ss4HHSp(N,
  M, # Recuendo no poderado
  r,  # tasa que afecta
  b, 
  rho = icc,
  P, 
  delta =  cve * z, #  Error estándar relativo,
  conf, m = 5:15)
  
  
  tabla_mue$M <- M
  tabla_mue$N <- N
  tabla_mue <- tabla_mue %>% relocate(M)
  tabla_mue <- tabla_mue %>% relocate(N)
  tabla_mue
  }
```


```{r}
df_parametrostablas_desempleo <- read_excel("ParametrosTablasMuestreo_Desempleo.xlsx") 
```



El tamaño de muestra nacional es:

```{r}
tabla_Nacional <- f_tablaMue("Nacional")
```

El tamaño de muestra por  área urbano:

```{r}
tabla_zonaUrbana <- f_tablaMue("Zona_Urbana")
```


El tamaño de muestra por  área rural:

```{r}
 tabla_zonaRural <- f_tablaMue("Zona_Rural")
```


El tamañpo de muestra por zonas:

```{r}
tabla_regionCentral <- f_tablaMue("Region_Central")
tabla_regionChorotega <- f_tablaMue("Region_Chorotega")
tabla_regionPacificaCentral <- f_tablaMue( "Region_Pacifica_Central")
tabla_regionBrunca <- f_tablaMue("Region_Brunca")
tabla_regionHuetarAtlantico <- f_tablaMue( "Region_Huetar_Atlantico")
tabla_regionHuetarNorte <- f_tablaMue("Región_Huetar_Norte")
```



# Comprobación sumas


```{r}
tabla_Nacional$Agregacion <- "Nacional"

tabla_zonaUrbana$Agregacion <- "Urbano"
tabla_zonaRural$Agregacion <- "Rural"

tabla_regionCentral$Agregacion <- "Region Central"
tabla_regionChorotega$Agregacion <- "Region Chorotega"
tabla_regionPacificaCentral$Agregacion <- "Region Pacífica - Central"
tabla_regionBrunca$Agregacion <- "Region Brunca"
tabla_regionHuetarAtlantico$Agregacion <- "Region Huetar Atlántico"
tabla_regionHuetarNorte$Agregacion <- "Region Huetar Norte"


tabla_Nacional <- tabla_Nacional %>% relocate(Agregacion)

tabla_zonaUrbana <- tabla_zonaUrbana %>% relocate(Agregacion)
tabla_zonaRural <-  tabla_zonaRural %>% relocate(Agregacion)

tabla_regionCentral <- tabla_regionCentral %>% relocate(Agregacion)
tabla_regionChorotega <- tabla_regionChorotega %>% relocate(Agregacion)
tabla_regionPacificaCentral <- tabla_regionPacificaCentral %>% relocate(Agregacion)
tabla_regionBrunca <- tabla_regionBrunca %>% relocate(Agregacion)
tabla_regionHuetarAtlantico <- tabla_regionHuetarAtlantico %>% relocate(Agregacion)
tabla_regionHuetarNorte <- tabla_regionHuetarNorte %>% relocate(Agregacion)


tabla_consolidado <- rbind(tabla_Nacional[4,], 
                        tabla_zonaUrbana[4,], tabla_zonaRural[4,],
                        tabla_regionCentral[4,], tabla_regionChorotega[4,], 
                        tabla_regionPacificaCentral[4,] ,
                        tabla_regionBrunca[4,], tabla_regionHuetarAtlantico[4,],
                        tabla_regionHuetarNorte[4,])
```


```{r}
write_xlsx(tabla_consolidado, "tabla_consolidado_desocupacion.xlsx")
```

