---
title: "Tasa de desocupación"
author: "CEPAL"
date: "2023-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(samplesize4surveys)
library(writexl)
```

Calculamos la encuesta de muestreo nacional:
```{r}
# Efecto diseño de la encuesta

# Resultados de SPSS
N <- 2484855
M <- 23484
P = 0.1195
cve <- 0.026
conf <- 0.95
r1 <- 0.6
r2 <- 0.79
b <-  3.040368  # Personas por hogar
deff <- 3.855
nro_vivXUPM <- 10.06
PM <- 0.08 # Perdida de Muestra
TR <- 0.89 # Tasa de resupesta



# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_nnal <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_nnal$HogEfect <- tm_pe_nnal$HouseholdsInSample / ((1-PM) * TR)
```




Calculamos para el área urbana:

```{r}
# Efecto diseño de la encuesta

# Resultados de SPSS
N <- 1862283
M <- 12798
P = 0.1181
cve <- 0.031
conf <- 0.95
r1 <- 0.62
r2 <- 0.8
b <-  3.031809  # Personas por hogar
deff <- 3.671
nro_vivXUPM <- 9.838178
PM <- 0.08 # Perdida de Muestra
TR <- 0.87 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_urbano <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_urbano$HogEfect <- tm_pe_urbano$HouseholdsInSample / ((1-PM) * TR)
```



Calculamos para el área rural:

```{r}
# Resultados de SPSS
N <- 622572
M <- 10686
P = 0.1237
cve <- 0.031
conf <- 0.95
r1 <- 0.57
r2 <- 0.76
b <-  3.06229  # Personas por hogar
deff <- 1.528

nro_vivXUPM <- 10.323601
PM <- 0.08 # Perdida de Muestra
TR <- 0.92 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_rural <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_rural$HogEfect <- tm_pe_rural$HouseholdsInSample / ((1-PM) * TR)
```



# Regiones 

# Región central

```{r}
# Resultados de SPSS
N <- 1643721
M <- 4626
P = 0.1163
cve <- 0.046
conf <- 0.95
r1 <- 0.63
r2 <- 0.8
b <-  3.0496  # Personas por hogar
deff <- 1.788


nro_vivXUPM <- 9.930393
PM <- 0.07 # Perdida de Muestra
TR <- 0.86 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionCentral <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionCentral$HogEfect <- tm_pe_regionCentral$HouseholdsInSample / ((1-PM) * TR)
```



# Región Chorotega

```{r}
# Resultados de SPSS
N <- 174448
M <- 3812
P = 0.1330
cve <- 0.046
conf <- 0.95
r1 <- 0.56
r2 <- 0.76
b <-  3.069563  # Personas por hogar
deff <- 1.738



nro_vivXUPM <- 10.326338
PM <- 0.07 # Perdida de Muestra
TR <- 0.92 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionChorotega <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionChorotega$HogEfect <- tm_pe_regionChorotega$HouseholdsInSample / ((1-PM) * TR)
```


# Región Pacífica Central


```{r}
# Resultados de SPSS
N <- 139180
M <- 2816
P = 0.0987
cve <- 0.046
conf <- 0.95
r1 <- 0.57
r2 <- 0.78
b <-  2.978529  # Personas por hogar
deff <- 1.342




nro_vivXUPM <- 9.848366
PM <- 0.08 # Perdida de Muestra
TR <- 0.85 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionPacificaCentral <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionPacificaCentral$HogEfect <- tm_pe_regionPacificaCentral$HouseholdsInSample / ((1-PM) * TR)
```


# Región Brunca


```{r}
# Resultados de SPSS
N <- 148152
M <- 3971
P = 0.1182
cve <- 0.046
conf <- 0.95
r1 <- 0.52
r2 <- 0.77
b <-  2.904828  # Personas por hogar
deff <- 1.3




nro_vivXUPM <- 10.156887
PM <- 0.1 # Perdida de Muestra
TR <- 0.92 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionBrunca <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionBrunca$HogEfect <- tm_pe_regionBrunca$HouseholdsInSample / ((1-PM) * TR)
```



# Región Huetar Atlántico

```{r}
# Resultados de SPSS
N <- 193901
M <- 4297
P = 0.1133
cve <- 0.046
conf <- 0.95
r1 <- 0.55
r2 <- 0.75
b <-  2.997394  # Personas por hogar
deff <- 1.506




nro_vivXUPM <- 9.892716
PM <- 0.08 # Perdida de Muestra
TR <- 0.87 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionHuetarAtlantico <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionHuetarAtlantico$HogEfect <- tm_pe_regionHuetarAtlantico$HouseholdsInSample / ((1-PM) * TR)
```


# Huetar Norte


```{r}
# Resultados de SPSS
N <- 185453
M <- 3962
P = 0.1583
cve <- 0.046
conf <- 0.95
r1 <- 0.57
r2 <- 0.75
b <-  3.167365  # Personas por hogar
deff <- 1.339




nro_vivXUPM <- 10.18425
PM <- 0.09 # Perdida de Muestra
TR <- 0.92 # Tasa de resupesta


# Calculamos alpha, z, icc
r <- r1  * r2 # Tasa de población afectada (dado que es un parámetro a nivel de hogar)
nbarra_encuesta <- nro_vivXUPM * b * r # Personas
alpha <- 1 - conf
z <- qnorm(1-alpha/2)
icc <- (deff - 1) / (nbarra_encuesta - 1) 
  
# Tabla de muestreo 
tm_pe_regionHuetarNorte <- ss4HHSp(N,
M, # Recuendo no poderado
r,  # tasa que afecta
b, 
rho = icc,
P, 
delta =  cve * z, #  Error estándar relativo,
conf, m = 5:10)

# De 10 casas se encuentra 9.3 y de esas el 86 le contesta para una tasa efectiva de 0.93 * 0.86
tm_pe_regionHuetarNorte$HogEfect <- tm_pe_regionHuetarNorte$HouseholdsInSample / ((1-PM) * TR)
```



# Comprobación sumas


```{r}
tm_pe_nnal$Agregacion <- "Nacional"
tm_pe_urbano$Agregacion <- "Urbano"
tm_pe_rural$Agregacion <- "Rural"

tm_pe_regionCentral$Agregacion <- "Region Central"
tm_pe_regionChorotega$Agregacion <- "Region Chorotega"
tm_pe_regionPacificaCentral$Agregacion <- "Region Pacífica - Central"
tm_pe_regionBrunca$Agregacion <- "Region Brunca"
tm_pe_regionHuetarAtlantico$Agregacion <- "Region Huetar Atlántico"
tm_pe_regionHuetarNorte$Agregacion <- "Region Huetar Norte"


tm_pe_nnal <- tm_pe_nnal %>% relocate(Agregacion)

tm_pe_urbano <- tm_pe_urbano %>% relocate(Agregacion)
tm_pe_rural <-  tm_pe_rural %>% relocate(Agregacion)

tm_pe_regionCentral <- tm_pe_regionCentral %>% relocate(Agregacion)
tm_pe_regionChorotega <- tm_pe_regionChorotega %>% relocate(Agregacion)
tm_pe_regionPacificaCentral <- tm_pe_regionPacificaCentral %>% relocate(Agregacion)
tm_pe_regionBrunca <- tm_pe_regionBrunca %>% relocate(Agregacion)
tm_pe_regionHuetarAtlantico <- tm_pe_regionHuetarAtlantico %>% relocate(Agregacion)
tm_pe_regionHuetarNorte <- tm_pe_regionHuetarNorte %>% relocate(Agregacion)


tm_consolidado <- rbind(tm_pe_nnal[4,], 
                        tm_pe_urbano[4,], tm_pe_rural[4,],
                        tm_pe_regionCentral[4,], tm_pe_regionChorotega[4,], 
                        tm_pe_regionPacificaCentral[4,] ,
                        tm_pe_regionBrunca[4,], tm_pe_regionHuetarAtlantico[4,],
                        tm_pe_regionHuetarNorte[4,])


```



```{r}
write_xlsx(tm_consolidado, "tm_consolidado_desocupacion.xlsx")
```

